linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - "^print$"
      - "^println$"
issues:
  exclude-dirs-use-default: false
  exclude-rules:
    - path: cmd/lekko/main.go
      text: "File is not `goimports`-ed"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    # - depguard
    - dogsled
    - errcheck
    - execinquery
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gochecknoinits
    - gofmt
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    # - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - nosprintfhostport
    - predeclared
    - promlinter
    - rowserrcheck
    - staticcheck
      # - stylecheck
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace
    - unparam
  disable-all: true
