// Copyright 2022 Lekko Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package repo

import (
	"os"
	"path/filepath"

	"github.com/pkg/errors"
	"gopkg.in/yaml.v3"
)

// Schema for a Lekko lockfile to be placed/managed in projects that use native
// lang for Lekko
type LekkoLock struct {
	// The latest pushed commit SHA in the config repo from the perspective of
	// the code repo. Allows stable regeneration and correct 3-way merges.
	Commit string
	// TODO: Maybe consider adding more repo info here to "connect" code
	// and config repos better
}

// Looks for, and reads, a `lekko.lock` file in the given path
func ReadLekkoLock(path string) (*LekkoLock, error) {
	f, err := os.ReadFile(filepath.Join(path, "lekko.lock"))
	if err != nil {
		return nil, err
	}
	l := &LekkoLock{}
	if err := yaml.Unmarshal(f, l); err != nil {
		return nil, err
	}
	if l.Commit == "" {
		return nil, errors.New("invalid commit hash in lockfile")
	}
	return l, nil
}

// Writes a file `lekko.lock` with the YAML-marshaled contents to the given path
func (l *LekkoLock) WriteFile(path string) error {
	f, err := os.OpenFile(filepath.Join(path, "lekko.lock"), os.O_CREATE|os.O_RDWR|os.O_TRUNC, 0666)
	if err != nil {
		return err
	}
	defer f.Close()
	// Preamble
	if _, err := f.WriteString("# This file is generated by running `lekko push` from your project.\n"); err != nil {
		return errors.Wrap(err, "write preamble")
	}
	// Write contents
	enc := yaml.NewEncoder(f)
	if err := enc.Encode(l); err != nil {
		return err
	}
	return nil
}
