name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        run: git config --global --add url."https://lekkoci:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_API_TOKEN }}
          github_token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
      - name: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: go-cache
        uses: actions/cache@v4
        with:
          # Go bin cache, mod cache, build cache, etc. - these are custom set by makego
          # which is why actions/setup-go can't handle caching properly
          # Also hash by makefiles because some things (like golangcilint version) are defined there
          path: |
            ~/.cache/core/${{ runner.os }}/x86_64/bin
            ~/.cache/core/${{ runner.os }}/x86_64/go/pkg/mod
            ~/.cache/core/${{ runner.os }}/x86_64/gocache
            ~/.cache/core/${{ runner.os }}/x86_64/include
            ~/.cache/core/${{ runner.os }}/x86_64/versions
            ~/.cache/core/${{ runner.os }}/x86_64/golangci-lint
          key: go-cache-core-${{ hashFiles('go.sum', 'make/**') }}
          restore-keys: go-cache-core-
      - name: ci
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        run: make ci
