name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        run: git config --global --add url."https://lekkoci:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - name: setup-go
        if: success()
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.0
      - name: ci
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        if: success()
        run: make ci
