name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        run: git config --global --add url."https://lekkoci:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: bufbuild/buf-setup-action@v1
        with:
          buf_user: ${{ secrets.BUF_USER }}
          buf_api_token: ${{ secrets.BUF_API_TOKEN }}
          github_token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
      - name: setup-go
        if: success()
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: ci
        env:
          GITHUB_TOKEN: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
        if: success()
        run: make ci
