name: buf-push
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-push-action@v1
        with:
          input: proto
          buf_token: ${{ secrets.BUF_API_TOKEN }}
